# Generated by Django 6.0.7 on 2026-08-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccine',
            new_name='RegistroVacina',
        ),
        migrations.RenameField(
            model_name='registrovacina',
            old_name='nome',
            new_name='nome_vacina',
        ),
        migrations.RemoveField(
            model_name='registrovacina',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='registrovacina',
            name='observacoes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelOptions(
            name='registrovacina',
            options={
                'verbose_name': 'Registro de vacina',
                'verbose_name_plural': 'Registros de vacina',
            },
        ),
    ]
