# Generated by Django 5.2.14 on 2026-08-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Pássaro', 'Pássaro'), ('Roedor', 'Roedor'), ('Outro', 'Outro')], max_length=50),
        ),
    ]
