# Generated by Django 6.0.7 on 2026-08-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='peso',
            field=models.FloatField(),
        ),
    ]
