# Generated by Codex on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_dono_delete_usuario"),
        ("pets", "0003_alter_pet_peso"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="usuario",
            new_name="dono",
        ),
        migrations.AlterField(
            model_name="pet",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="accounts.dono",
            ),
        ),
    ]
