# Generated by Django 6.0.7 on 2026-08-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigoblog',
            name='imagem_url',
        ),
        migrations.RemoveField(
            model_name='artigoblog',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='artigoblog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='artigoblog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='artigoblog',
            name='tempo_leitura',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
