# Generated by Django 6.1 on 2026-08-25 17:21

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_usuarios_para_donos(apps, schema_editor):
    Usuario = apps.get_model("accounts", "Usuario")
    Dono = apps.get_model("accounts", "Dono")

    for usuario in Usuario.objects.all():
        Dono.objects.update_or_create(
            user_ptr_id=usuario.id,
            defaults={
                "cpf": usuario.cpf,
                "telefone": usuario.telefone,
                "cep": usuario.cep,
                "logradouro": usuario.logradouro,
                "numero": usuario.numero,
                "complemento": usuario.complemento,
                "bairro": usuario.bairro,
                "cidade": usuario.cidade,
                "estado": usuario.estado,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_convert_profile_to_custom_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'dono',
                'verbose_name_plural': 'donos',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(copiar_usuarios_para_donos, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
